#==========================================================================
#	ファイルの中身を C# のバイト配列として埋め込む（Unity のプレイヤー用テストが .atsb を読むため）
#	cmake -DINPUT=<ファイル> -DOUTPUT=<.cs> -DNAMESPACE=<名前空間> -DCLASS=<クラス> -DSOURCE=<元の .ats> -P embed_csharp_bytes.cmake
#	中身が同じなら書き換えない（Unity の再コンパイルを避ける）。改行は OS によらず LF にする。
#	引数は ASCII だけにする（Visual Studio のビルドはカスタムコマンドを cp932 のバッチで実行するので、日本語が化ける）
#==========================================================================
cmake_minimum_required( VERSION 3.16 )		# -P で動かすときもポリシーを決める

file( READ "${INPUT}" hex HEX )
string( LENGTH "${hex}" len )
math( EXPR size "${len} / 2" )
# 1 行 32 バイト（64 文字）の文字列リテラルに分ける（CMake の正規表現には {n} が無い）
string( REPEAT "[0-9a-f]" 64 line )
string( REGEX REPLACE "(${line})" "\\1\"\n\t\t\t+ \"" body "${hex}" )
string( REGEX REPLACE "\"\n\t\t\t\\+ \"$" "" body "${body}" )		# ちょうど 32 バイトの倍数のとき末尾に残る区切りを消す

set( text "// <auto-generated>
// ${SOURCE} をコンパイルした .atsb（${size} バイト）。CMake のビルドで tools/cmake/embed_csharp_bytes.cmake が生成する。手で編集しない。
// </auto-generated>
namespace ${NAMESPACE}
{
	public static class ${CLASS}
	{
		const string kHex =
			\"${body}\";

		public static byte[] Bytes()
		{
			var b = new byte[ kHex.Length / 2 ];
			for( int i = 0; i < b.Length; ++i ) b[i] = System.Convert.ToByte( kHex.Substring( i * 2, 2 ), 16 );
			return b;
		}
	}
}
" )
# file( WRITE ) は Windows で CRLF になるので、configure_file で LF に揃える
string( REGEX REPLACE "\n$" "" text "${text}" )		# configure_file が最後の行に改行を足すので、ここで 1 つ落とす
file( WRITE "${OUTPUT}.in" "@text@" )
configure_file( "${OUTPUT}.in" "${OUTPUT}.tmp" @ONLY NEWLINE_STYLE UNIX )
execute_process( COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUTPUT}.tmp" "${OUTPUT}" )
file( REMOVE "${OUTPUT}.in" "${OUTPUT}.tmp" )
